### ISSUE TITLE
Rendering folder is missing

### ISSUE THREAD

**Issue by Sopwafel** [yoctopuce-examples/WeighScaleCalibration#1]
The solution refers to 5 files in the "YDataRenderer" folder, but this entire folder is missing from the Git.
The files my VS is complaining about are:

- YAngularGauge.cs
- YDataRendererCommon.cs
- YDigitalDisplay.cs
- YGraph.cs
- YSolidGauge.cs

**Comment by yoctopuce** [comment]
This tools is deprecated, we have now a better application Yocto-BridgeCalibration
which is also available on GitHub: https://github.com/yoctopuce/Yocto-BridgeCalibration
